language: crystal
addons:
  chrome: stable
before_install:
  - sudo apt-get install chromium-chromedriver
  - sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - crystal spec
  - crystal tool format --check
  - crystal docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: webdriver_pump
  on:
    branch: master
  local_dir: docs
