name: Crystal Specs
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install driver for Firefox
        uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Shards install
        run: |
          shards install
      - name: Run specs
        env:
          CI: true
          RUN_ON: firefox
        run: |
          crystal spec --error-trace --progress
